[wip] update to rustc_private 2023-06-10
current errors:
```
 1  error[E0432]: unresolved import `rustc_hir::def_id::DefIndexAddressSpace`
  --> src/print.rs:8:52
 2  error[E0603]: module `rmeta` is private
  --> src/driver.rs:5:21
  --> /home/jyn/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/compiler/rustc_metadata/src/lib.rs:36:1
 3  error[E0603]: module `rmeta` is private
  --> src/print.rs:9:21
  --> /home/jyn/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/compiler/rustc_metadata/src/lib.rs:36:1
 4  error[E0599]: no method named `crate_data_as_rc_any` found for struct `TyCtxt<'tcx>` in the current scope
   --> src/driver.rs:88:26
 5  error[E0618]: expected function, found `impl for<'b> FnOnce(&'b CrateMetadata)`
   --> src/driver.rs:89:5
 6  error[E0599]: no function or associated item named `from_array_index` found for struct `DefIndex` in the current scope
    --> src/print.rs:312:31
```

some of these are just because `CrateMetadata` is private now and its methods are on TyCtxt, but some of them are real - `DefIndex` has no public constructors anymore and `CrateRoot` is private to `rustc_metadata`.